spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eastbranchmanagement
    username: report_builder
    password: build_reporter
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: report
  liquibase:
    default-schema: report
    change-log: classpath:db/changelog/db.master-changelog.xml

  kafka:
    bootstrap-servers: localhost:29013
    template:
      default-topic: topic-transaction-report
    consumer:
      group-id: group-id-transaction-report